# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line. Check Gradle settings in the IDE or in gradle.properties.

android.useAndroidX=true
android.enableJetifier=true

# Keep the original file structure
org.gradle.jvmargs=-Xmx2048m

# Enable cache
#android.enableBuildCache=true

# Kotlin options
kotlin.incremental=true
